/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KidRecommender {
        /**
          * Kunci otentikasi
         */
        "authKey": string;
        /**
          * Setelan untuk mengakomodasi mode terang/gelap
         */
        "darkMode": boolean;
        /**
          * Lokasi penempatan komponen
         */
        "position": string;
        /**
          * Label/tagar jamak artikel yang dipisahkan dengan koma. Kalau tidak diisi, komponen akan mengambil nilai `<meta name="keyword" />`.
         */
        "postTags": string;
        /**
          * Judul artikel. Kalau tidak diisi, komponen akan otomatis mengambil nilai `<meta name="og:title" />` atau `<title />`.
         */
        "postTitle": string;
        /**
          * URL artikel tempat komponen ini disisipkan. Kalau tidak diisi, komponen akan otomatis mengambil nilai `<meta property="og:url" />` atau `window.location`.
         */
        "postUrl": string;
        /**
          * Rubrik/kategori artikel, pisahkan tiap item dengan koma (,)
         */
        "section": string;
    }
}
declare global {
    interface HTMLKidRecommenderElement extends Components.KidRecommender, HTMLStencilElement {
    }
    var HTMLKidRecommenderElement: {
        prototype: HTMLKidRecommenderElement;
        new (): HTMLKidRecommenderElement;
    };
    interface HTMLElementTagNameMap {
        "kid-recommender": HTMLKidRecommenderElement;
    }
}
declare namespace LocalJSX {
    interface KidRecommender {
        /**
          * Kunci otentikasi
         */
        "authKey": string;
        /**
          * Setelan untuk mengakomodasi mode terang/gelap
         */
        "darkMode"?: boolean;
        /**
          * Lokasi penempatan komponen
         */
        "position"?: string;
        /**
          * Label/tagar jamak artikel yang dipisahkan dengan koma. Kalau tidak diisi, komponen akan mengambil nilai `<meta name="keyword" />`.
         */
        "postTags"?: string;
        /**
          * Judul artikel. Kalau tidak diisi, komponen akan otomatis mengambil nilai `<meta name="og:title" />` atau `<title />`.
         */
        "postTitle"?: string;
        /**
          * URL artikel tempat komponen ini disisipkan. Kalau tidak diisi, komponen akan otomatis mengambil nilai `<meta property="og:url" />` atau `window.location`.
         */
        "postUrl"?: string;
        /**
          * Rubrik/kategori artikel, pisahkan tiap item dengan koma (,)
         */
        "section"?: string;
    }
    interface IntrinsicElements {
        "kid-recommender": KidRecommender;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kid-recommender": LocalJSX.KidRecommender & JSXBase.HTMLAttributes<HTMLKidRecommenderElement>;
        }
    }
}
